#!/usr/bin/env bash
# Displays Best School ten times
# Uses while loop and if statement
# if statement displays Hi in 9th iteration

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
