#!/usr/bin/env bash
# Displays bad luck for forth iteration
# Displays good luck for eigth iteration
# Displays Best School for other iterations

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
