#!/usr/bin/env bash
# Displays number 1 to 20
# Displays "bad luck from china in 4th count"
# Displays "badluck from Japan" in 8th count
# Displays "badluck from Italy" in 17th count

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
